; ========== 公共配置 ==========
[env]
platform = espressif32
board = esp32dev
framework = arduino

; 串口监视器
monitor_port = /dev/cu.usbserial-0001
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

; Flash 配置（兼容克隆板 Flash 芯片）
board_build.flash_mode = dout
board_build.f_flash = 40000000L

; 库依赖
lib_deps = 
    bblanchon/ArduinoJson@^7.0.0
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14
    bodmer/TFT_eSPI@^2.5.34
    arduino-libraries/NTPClient@^3.2.1
    sui77/rc-switch@^2.6.4

; 构建选项
build_flags = 
    -DCORE_DEBUG_LEVEL=3
    -DUSER_SETUP_LOADED
    -DILI9341_DRIVER
    -DTFT_CS=15
    -DTFT_DC=2
    -DTFT_RST=22
    -DTFT_MOSI=23
    -DTFT_SCLK=18
    -DTFT_MISO=-1
    -DTFT_BL=21
    -DSPI_FREQUENCY=40000000
    -DLOAD_GLCD
    -DLOAD_FONT2
    -DLOAD_FONT4
    -DLOAD_FONT6
    -DLOAD_FONT7
    -DLOAD_FONT8
    -DLOAD_GFXFF
    -DSMOOTH_FONT

; ========== USB 有线上传 ==========
[env:esp32dev]
upload_protocol = esptool
upload_port = /dev/cu.usbserial-0001
upload_speed = 115200

; ========== OTA 无线上传 ==========
[env:esp32dev_ota]
upload_protocol = espota
upload_port = 192.168.1.43
upload_flags =
    --port=3232
